# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JsonTransitionToModel' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'YYModel', '~> 1.0.4'
  # Pods for JsonTransitionToModel

  target 'JsonTransitionToModelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JsonTransitionToModelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
